# Generated by Django 5.2.12 on 2026-08-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('TRANSGENDER', 'Transgender')], default='', max_length=20)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('annual_family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('STUDENT', 'Student'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('PRIVATE_JOB', 'Private Job'), ('GOVT_JOB', 'Government Job'), ('LABOURER', 'Daily Wage Labourer'), ('BUSINESS', 'Small Business / Artisan'), ('HOMEMAKER', 'Homemaker'), ('OTHER', 'Other')], default='', max_length=50)),
                ('education_level', models.CharField(blank=True, choices=[('BELOW_10TH', 'Below 10th Standard'), ('10TH_PASS', '10th Pass (SSLC)'), ('12TH_PASS', '12th Pass (HSC/Intermediate)'), ('DIPLOMA', 'Diploma / ITI'), ('GRADUATE', "Graduate (Bachelor's Degree)"), ('POST_GRADUATE', "Post Graduate (Master's Degree)"), ('DOCTORATE', 'Ph.D. / Doctorate'), ('OTHER', 'Other')], default='', max_length=50)),
                ('is_student', models.BooleanField(default=False)),
                ('is_farmer', models.BooleanField(default=False)),
                ('land_ownership', models.BooleanField(default=False)),
                ('land_holding_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caste_category', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('OBC', 'Other Backward Class (OBC)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('EWS', 'Economically Weaker Section (EWS)'), ('OTHER', 'Other')], default='', max_length=20)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disability_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single / Unmarried'), ('MARRIED', 'Married'), ('WIDOW', 'Widow / Widower'), ('DIVORCED', 'Divorced / Separated')], default='', max_length=20)),
                ('employment_status', models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self-Employed'), ('STUDENT', 'Student')], default='', max_length=20)),
                ('bpl_card_holder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
