# Generated by Django 5.2.12 on 2026-08-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(help_text='Target attribute e.g. age, annual_family_income, state, occupation, is_farmer, is_student, land_ownership, caste_category, is_disabled, bpl_card_holder', max_length=100)),
                ('operator', models.CharField(choices=[('=', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equal To'), ('<=', 'Less Than or Equal To'), ('IN', 'In List (Comma-separated)'), ('NOT IN', 'Not In List')], default='=', max_length=10)),
                ('value', models.CharField(help_text='Target rule value e.g. 18, 500000, Maharashtra, Karnataka, True, FEMALE', max_length=500)),
                ('value_type', models.CharField(choices=[('STRING', 'String / Text'), ('NUMBER', 'Number / Currency'), ('BOOLEAN', 'Boolean (True/False)'), ('LIST', 'List of Options')], default='STRING', max_length=20)),
                ('description', models.CharField(help_text='Human-readable rule explanation e.g. Annual family income must be under ₹5,00,000', max_length=255)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether rule failure invalidates scheme eligibility completely')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='schemes.governmentscheme')),
            ],
        ),
    ]
