# Generated by Django 5.2.12 on 2026-10-06 14:28

import apps.eligibility.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
        ('schemes', '0002_schemenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(default=apps.eligibility.models.generate_verification_id, editable=False, max_length=16, unique=True)),
                ('eligibility_score', models.IntegerField(default=0)),
                ('criteria_snapshot', models.JSONField(blank=True, default=list)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_certificates', to='schemes.governmentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
