# Generated by Django 5.2.12 on 2026-08-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(help_text='Unique Scheme ID/Slug e.g. pm-kisan', max_length=100, unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FARMER', 'Farmers & Agriculture'), ('EDUCATION', 'Education & Student Welfare'), ('WOMEN_CHILD', 'Women & Child Welfare'), ('HEALTHCARE', 'Healthcare & Health Insurance'), ('EMPLOYMENT', 'Employment & Livelihood'), ('HOUSING', 'Housing & Urban Infrastructure'), ('SENIOR_CITIZEN', 'Senior Citizens & Pension'), ('SKILL_DEV', 'Skill Development & Entrepreneurship'), ('OTHER', 'Other Welfare Schemes')], max_length=50)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('ministry', models.CharField(help_text='Ministry or Nodal Department', max_length=255)),
                ('scheme_type', models.CharField(choices=[('CENTRAL', 'Central Sector Scheme'), ('STATE', 'State Sponsored Scheme'), ('JOINT', 'Centrally Sponsored Scheme (Joint)')], default='CENTRAL', max_length=20)),
                ('applicable_state', models.CharField(default='All India', help_text="Specific state or 'All India'", max_length=100)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True, default='')),
                ('objective', models.TextField(blank=True, default='')),
                ('benefits', models.TextField()),
                ('benefit_type', models.CharField(choices=[('FINANCIAL', 'Direct Financial Assistance / Cash Transfer'), ('SUBSIDY', 'Subsidy / Price Support'), ('SCHOLARSHIP', 'Scholarship / Fellowship'), ('PENSION', 'Pension / Annuity'), ('LOAN', 'Subsidized Loan / Credit Facility'), ('IN_KIND', 'In-Kind Assistance / Equipment / Goods'), ('CERTIFICATE', 'Certificate / Skill Training'), ('OTHER', 'Other Support')], default='FINANCIAL', max_length=30)),
                ('benefit_amount', models.CharField(blank=True, default='', help_text='e.g. ₹6,000 / year or 100% Fee Waiver', max_length=255)),
                ('application_mode', models.CharField(choices=[('ONLINE', 'Online Portal'), ('OFFLINE', 'Physical Office / CSC Centre'), ('HYBRID', 'Online & Offline Available')], default='ONLINE', max_length=20)),
                ('application_link', models.URLField(help_text='Direct link to official application portal', max_length=500)),
                ('official_website', models.URLField(help_text='Main official government website URL', max_length=500)),
                ('official_guidelines_pdf', models.URLField(blank=True, default='', help_text='Link to official PDF circular', max_length=500)),
                ('helpline', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('scheme_status', models.CharField(choices=[('ACTIVE', 'Active / Accepting Applications'), ('INACTIVE', 'Inactive / Temporarily Suspended'), ('UPCOMING', 'Upcoming Scheme'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('launch_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_demo_data', models.BooleanField(default=True, help_text='Flag indicating whether scheme is sample demo data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='schemes.governmentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
