# Generated by Django 5.2.12 on 2026-08-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(help_text='e.g. Aadhaar Card, Income Certificate, Bank Passbook', max_length=255)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mandatory or optional document')),
                ('description', models.TextField(blank=True, default='', help_text='Guidance on where or how to procure this document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='schemes.governmentscheme')),
            ],
        ),
    ]
